### ISSUE TITLE
Error for running the code

### ISSUE THREAD

**Issue by Jimmy-7664** [GestaltCogTeam/STEP#12]
I've got several errors while running the code.
a). 
For the forecasting part, 
1) I run the following command as written in the Readme.md "python step/run.py --cfg='step/step_METR-LA.py' --gpus='0'" then I got 
2022-09-29 15:15:25,915 - easytorch-launcher - INFO - Launching EasyTorch training.
Traceback (most recent call last):
  File "step/run.py", line 20, in <module>
    launch_training(args.cfg, args.gpus)
  File "/home/ght/tsformer/STEP/basicts/launcher.py", line 19, in launch_training
    easytorch.launch_training(cfg=cfg, gpus=gpus, node_rank=node_rank)
  File "/home/ght/anaconda3/envs/torch/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 58, in launch_training
    cfg = init_cfg(cfg, node_rank == 0)
  File "/home/ght/anaconda3/envs/torch/lib/python3.8/site-packages/easytorch/config/utils.py", line 210, in init_cfg
    cfg = import_config(cfg, verbose=save)
  File "/home/ght/anaconda3/envs/torch/lib/python3.8/site-packages/easytorch/config/utils.py", line 173, in import_config
    cfg = __import__(path, fromlist=[cfg_name]).CFG
ModuleNotFoundError: No module named 'step.step_METR-LA'
2) There seems only one dataset's scripts (METR-LA), no scripts for others like PEMS04 ets.

b). 
For the pretraining part,
I run  "python step/run.py --cfg='step/TSFormer_METR-LA.py' --gpus='0,1,2,3'",
then I got

2022-09-29 15:05:58,680 - easytorch-training - ERROR - Traceback (most recent call last):
  File "/home/ght/anaconda3/envs/torch/lib/python3.8/site-packages/easytorch/launcher/launcher.py", line 30, in training_func
    runner.train(cfg)
  File "/home/ght/anaconda3/envs/torch/lib/python3.8/site-packages/easytorch/core/runner.py", line 361, in train
    self.on_epoch_end(epoch)
  File "/home/ght/tsformer/STEP/basicts/runners/base_runner.py", line 141, in on_epoch_end
    if self.test_data_loader is not None and epoch % self.test_interval == 0:
AttributeError: 'TSFormerRunner' object has no attribute 'test_data_loader'

I check the scripts, it seems that test_data_loader is not defined.
How can I solve the above issues, looking forward to your reply.
: )

**Comment by zezhishao** [comment]
Thanks for your question~
1. This is a typo. The command line is case sensitive, so the correct command should be `python step/run.py --cfg='step/STEP_METR-LA.py' --gpus='0'`. 
2. STEP has just been refactored, and I'm testing other datasets (PEMS-BAY and PEMS04) to make sure there are no performance issues. However, my computing resources are limited, so it may take a few days. I will upload scripts for the PEMS04 and PEMS-BAY datasets very soon.
3. I can not reproduce this error in the latest version of STEP. The test_data_loader is built in [here](https://github.com/zezhishao/STEP/blob/7c56a949a37c17098cd90afeecb27dd52170cbb8/basicts/runners/base_runner.py#L94). Could you provide more information?

**Comment by zezhishao** [comment]
For the third question, I [added the initialization of `test_data_loader`](https://github.com/zezhishao/STEP/commit/dc8ba47187a13d5743fb98e1b8e2bf1b74c64a79) to avoid possible problems after you edit the config file (e.g., remove all arguments related to the test process).

**Comment by Jimmy-7664** [comment]
Thanks for your timely reply. Due to the limitation of computing resources, I will try again tomorrow.

**Comment by zezhishao** [comment]
Testing on all these datasets has now been completed.
You can now find configurations for all datasets.
Moreover, our training logs are shown in [training_logs/TSFormer_METR-LA.log](https://github.com/zezhishao/STEP/blob/github/training_logs/TSFormer_METR-LA.log), [training_logs/TSFormer_PEMS04.log](https://github.com/zezhishao/STEP/blob/github/training_logs/TSFormer_PEMS04.log), and [training_logs/TSFormer_PEMS04.log](https://github.com/zezhishao/STEP/blob/github/training_logs/TSFormer_PEMS-BAY.log), and the our pre-trained TSFormers for each datasets are placed in `tsformer_ckpt` folder.
