### ISSUE TITLE
ModuleNotFoundError: No module named "'step"

### ISSUE THREAD

**Issue by 1154761334** [GestaltCogTeam/STEP#25]
Hello, I have some problems running the training model. After I installed the requirements and processed the data as required, the following errors occurred in the training for the model:

input:
!python step/run.py --cfg='step/STEP_METR-LA.py' --gpus='0'

output:
2022-12-05 11:06:42,782 - easytorch-launcher - INFO - Launching EasyTorch training.
Traceback (most recent call last):
  File "D:\python-venv\STEP\step\run.py", line 26, in <module>
    launch_training(args.cfg, args.gpus)
  File "D:\python-venv\STEP\basicts\launcher.py", line 19, in launch_training
    easytorch.launch_training(cfg=cfg, gpus=gpus, node_rank=node_rank)
  File "D:\python-venv\venv\lib\site-packages\easytorch\launcher\launcher.py", line 80, in launch_training
    cfg = init_cfg(cfg, node_rank == 0)
  File "D:\python-venv\venv\lib\site-packages\easytorch\launcher\launcher.py", line 13, in init_cfg
    cfg = import_config(cfg, verbose=save)
  File "D:\python-venv\venv\lib\site-packages\easytorch\config.py", line 245, in import_config
    cfg = __import__(path, fromlist=[cfg_name]).CFG
ModuleNotFoundError: No module named "'step"

**Comment by zezhishao** [comment]
Please make sure to run the commands in the README in the directory `C:\path\to\STEP`, instead of `C:\path\to\STEP\step`.
Reference: Issue https://github.com/zezhishao/STEP/issues/17

**Comment by 1154761334** [comment]
Hi zezhishao，
 Thanks for your kind reply, I found that this problem may be caused by my device. When I run the **jupyter notebook** in the C:  path  to  STEP directory:! python step/run. py --cfg='step/STEP_ METR-LA. After py '-- gpus='0', you will get the same error as shown in the following ：

`2022-12-06 09:11:24,320 - easytorch-launcher - INFO - Launching EasyTorch training.
Traceback (most recent call last):
  File "D:\python-venv\STEP\step\run.py", line 26, in <module>
    launch_training(args.cfg, args.gpus)
  File "D:\python-venv\STEP\basicts\launcher.py", line 19, in launch_training
    easytorch.launch_training(cfg=cfg, gpus=gpus, node_rank=node_rank)
  File "D:\python-venv\venv\lib\site-packages\easytorch\launcher\launcher.py", line 80, in launch_training
    cfg = init_cfg(cfg, node_rank == 0)
  File "D:\python-venv\venv\lib\site-packages\easytorch\launcher\launcher.py", line 13, in init_cfg
    cfg = import_config(cfg, verbose=save)
  File "D:\python-venv\venv\lib\site-packages\easytorch\config.py", line 245, in import_config
    cfg = __import__(path, fromlist=[cfg_name]).CFG
ModuleNotFoundError: No module named "'step"`

**When running under the terminal, the expected effect is obtained：**

`2022-12-06 15:45:45,971 - easytorch-launcher - INFO - Launching EasyTorch training.
DESCRIPTION: STEP(METR-LA) configuration
RUNNER: <class 'step.step_runner.step_runner.STEPRunner'>
DATASET_CLS: <class 'step.step_data.forecasting_dataset.ForecastingDataset'>
DATASET_NAME: METR-LA
DATASET_TYPE: Traffic speed
DATASET_INPUT_LEN: 12
DATASET_OUTPUT_LEN: 12
DATASET_ARGS:
  seq_len: 2016
GPU_NUM: 1
ENV:
  SEED: 0
  CUDNN:
    ENABLED: True
MODEL:
  NAME: STEP
  ARCH: <class 'step.step_arch.step.STEP'>
  PARAM:
    dataset_name: METR-LA
    pre_trained_tsformer_path: tsformer_ckpt/TSFormer_METR-LA.pt
    tsformer_args:
      patch_size: 12
      in_channel: 1
      embed_dim: 96
      num_heads: 4
      mlp_ratio: 4
      dropout: 0.1
      num_token: 168.0
      mask_ratio: 0.75
      encoder_depth: 4
      decoder_depth: 1
      mode: forecasting
    backend_args:
      num_nodes: 207
      supports: [tensor([[0.2050, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.2626, 0.1503,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1027, 0.2095,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2788, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2645, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.1408]]), tensor([[0.2452, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1789, 0.0968,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1283, 0.2475,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.4463, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2833, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.1831]])]
      dropout: 0.3
      gcn_bool: True
      addaptadj: True
      aptinit: None
      in_dim: 2
      out_dim: 12
      residual_channels: 32
      dilation_channels: 32
      skip_channels: 256
      end_channels: 512
      kernel_size: 2
      blocks: 4
      layers: 2
    dgl_args:
      dataset_name: METR-LA
      k: 10
      input_seq_len: 12
      output_seq_len: 12
  FROWARD_FEATURES: [0, 1, 2]
  TARGET_FEATURES: [0]
  DDP_FIND_UNUSED_PARAMETERS: True
TRAIN:
  LOSS: step_loss
  OPTIM:
    TYPE: Adam
    PARAM:
      lr: 0.005
      weight_decay: 1e-05
      eps: 1e-08
  LR_SCHEDULER:
    TYPE: MultiStepLR
    PARAM:
      milestones: [1, 18, 36, 54, 72]
      gamma: 0.5
  CLIP_GRAD_PARAM:
    max_norm: 3.0
  NUM_EPOCHS: 100
  CKPT_SAVE_DIR: checkpoints\STEP_100
  DATA:
    DIR: datasets/METR-LA
    BATCH_SIZE: 8
    PREFETCH: False
    SHUFFLE: True
    NUM_WORKERS: 2
    PIN_MEMORY: True
  NULL_VAL: 0.0
  CL:
    WARM_EPOCHS: 0
    CL_EPOCHS: 6
    PREDICTION_LENGTH: 12
VAL:
  INTERVAL: 1
  DATA:
    DIR: datasets/METR-LA
    BATCH_SIZE: 8
    PREFETCH: False
    SHUFFLE: False
    NUM_WORKERS: 2
    PIN_MEMORY: True
TEST:
  INTERVAL: 1
  DATA:
    DIR: datasets/METR-LA
    BATCH_SIZE: 8
    PREFETCH: False
    SHUFFLE: False
    NUM_WORKERS: 2
    PIN_MEMORY: True

2022-12-06 15:45:46,423 - easytorch-env - INFO - Use GPUs 0.
2022-12-06 15:45:46,455 - easytorch-launcher - INFO - Initializing runner "<class 'step.step_runner.step_runner.STEPRunner'>"
2022-12-06 15:45:46,455 - easytorch-env - INFO - Disable TF32 mode
2022-12-06 15:45:46,455 - easytorch - INFO - Set ckpt save dir: 'checkpoints\STEP_100\53a27f003182ec852ca7bad1e6ca286a'
2022-12-06 15:45:46,455 - easytorch - INFO - Building model.
2022-12-06 15:45:47,139 - easytorch-training - INFO - Initializing training.
2022-12-06 15:45:47,139 - easytorch-training - INFO - Set clip grad, param: {'max_norm': 3.0}
2022-12-06 15:45:47,139 - easytorch-training - INFO - Building training data loader.
train len: 23974
2022-12-06 15:45:47,291 - easytorch-training - INFO - Set optim: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: False
    lr: 0.005
    maximize: False
    weight_decay: 1e-05
)
2022-12-06 15:45:47,292 - easytorch-training - INFO - Set lr_scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x000001774A382FA0>
2022-12-06 15:45:47,299 - easytorch-training - INFO - Initializing validation.
2022-12-06 15:45:47,300 - easytorch-training - INFO - Building val data loader.
val len: 3425
test len: 6850
2022-12-06 15:45:47,496 - easytorch-training - INFO - Epoch 1 / 100
  0%|                                                                                       `
