### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by kiang-codes** [GestaltCogTeam/STEP#39]
window系统，numpy== 1.22.3，  torch ==1.10 ，easytorch==1.2.10 ，很奇怪 这个错误两天了，尝试过对torch升级降级，尝试过对numpy升级降级，网上的方法都是说版本不兼容，改完还是一直跑不起来，不知道作者有没有遇到过相似的问题，或者解决思路，麻烦告知！！！ 辛苦了 ！ 非常谢谢！！

File "D:\project\STEP-github\basicts\launcher.py", line 20, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
TypeError: launch_training() got an unexpected keyword argument 'devices'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\launcher\launcher.py", line 52, in training_func
    runner.train(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\core\runner.py", line 333, in train
    self.init_training(cfg)
  File "D:\project\STEP-github\basicts\runners\base_tsf_runner.py", line 61, in init_training
    super().init_training(cfg)
  File "D:\project\STEP-github\basicts\runners\base_runner.py", line 86, in init_training
    super().init_training(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\core\runner.py", line 396, in init_training
    self.train_data_loader = self.build_train_data_loader(cfg)
  File "D:\project\STEP-github\basicts\runners\base_runner.py", line 63, in build_train_data_loader
    train_data_loader = super().build_train_data_loader(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\core\runner.py", line 162, in build_train_data_loader
    dataset = self.build_train_dataset(cfg)
  File "D:\project\STEP-github\basicts\runners\base_tsf_runner.py", line 111, in build_train_dataset
    dataset = cfg["DATASET_CLS"](**dataset_args)
  File "D:\project\STEP-github\basicts\data\dataset.py", line 21, in __init__
    self.data = torch.from_numpy(processed_data).float()
RuntimeError: Numpy is not available

Traceback (most recent call last):
  File "D:\project\STEP-github\basicts\launcher.py", line 20, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
TypeError: launch_training() got an unexpected keyword argument 'devices'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\STEP-github\step\run.py", line 26, in <module>
    launch_training(args.cfg, args.gpus)
  File "D:\project\STEP-github\basicts\launcher.py", line 24, in launch_training
    easytorch.launch_training(cfg=cfg, gpus=gpus, node_rank=node_rank)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\launcher\launcher.py", line 93, in launch_training
    train_dist(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\launcher\launcher.py", line 56, in training_func
    raise e
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\launcher\launcher.py", line 52, in training_func
    runner.train(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\core\runner.py", line 333, in train
    self.init_training(cfg)
  File "D:\project\STEP-github\basicts\runners\base_tsf_runner.py", line 61, in init_training
    super().init_training(cfg)
  File "D:\project\STEP-github\basicts\runners\base_runner.py", line 86, in init_training
    super().init_training(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\core\runner.py", line 396, in init_training
    self.train_data_loader = self.build_train_data_loader(cfg)
  File "D:\project\STEP-github\basicts\runners\base_runner.py", line 63, in build_train_data_loader
    train_data_loader = super().build_train_data_loader(cfg)
  File "C:\Users\123\AppData\Roaming\Python\Python310\site-packages\easytorch\core\runner.py", line 162, in build_train_data_loader
    dataset = self.build_train_dataset(cfg)
  File "D:\project\STEP-github\basicts\runners\base_tsf_runner.py", line 111, in build_train_dataset
    dataset = cfg["DATASET_CLS"](**dataset_args)
  File "D:\project\STEP-github\basicts\data\dataset.py", line 21, in __init__
    self.data = torch.from_numpy(processed_data).float()
RuntimeError: Numpy is not available

**Comment by zezhishao** [comment]
抱歉，我没有碰到过这个问题。
