### ISSUE TITLE
ModuleNotFoundError for easytorch

### ISSUE THREAD

**Issue by Jimmy-7664** [GestaltCogTeam/STEP#7]
When I run the following command, I get error.
I have already installed easytorch-3.4.7.

bash scripts/data_preparation/all.sh
Traceback (most recent call last):
  File "scripts/data_preparation/METR-LA/generate_training_data.py", line 12, in <module>
    from basicts.data.transform import standard_transform
  File "/home/ght/tsformer/STEP/basicts/data/__init__.py", line 3, in <module>
    from easytorch.utils.registry import scan_modules
ModuleNotFoundError: No module named 'easytorch.utils.registry'
Traceback (most recent call last):
  File "scripts/data_preparation/METR-LA/generate_training_data.py", line 12, in <module>
    from basicts.data.transform import standard_transform
  File "/home/ght/tsformer/STEP/basicts/data/__init__.py", line 3, in <module>
    from easytorch.utils.registry import scan_modules
ModuleNotFoundError: No module named 'easytorch.utils.registry'

What's the problem? Is it because of the version of easytorch? If so, then what is the right version number? 
Looking forward to your reply
: )

**Comment by zezhishao** [comment]
Sorry for this error. 
I will update `requirements.txt` and `readme.md` very soon.
Currently, you can install easytorch via `pip install easy-torch`.
Kindly note that it is `easy-torch`, instead of `easytorch`.
